### PR TITLE
fix(sdk): Examples not working

### LINKED ISSUE #941: [BUG] SDK examples not working
The examples of the SDK main functions are not working any more.

### PR DESCRIPTION
**Pull request by alainncls**
## What does this PR do?

- Fixes the TypeScript configuration
- Removes deprecated tests
- Fixes failing examples

### Related ticket

Fixes #941 

### Type of change

- [ ] Chore
- [X] Bug fix
- [ ] New feature
- [ ] Documentation update

## Check list

- [X] My&nbsp;contribution&nbsp;follows&nbsp;the&nbsp;project's&nbsp;[guidelines](https://github.com/Consensys/linea-attestation-registry/blob/dev/CONTRIBUTING.md)
- [ ] I have made corresponding changes to the documentation
- [ ] Unit tests for any smart contract change
- [ ] Contracts and functions are documented

### CODE REVIEW

File: sdk/examples/module/moduleExamples.ts [hunk 1]
```diff
@@ -10,22 +10,12 @@ export default class ModuleExamples {
 
   async run(argv: string, methodName: string = "", waitForConfirmation = false) {
     if (methodName.toLowerCase() == "findOneById".toLowerCase() || methodName == "") {
-      const moduleId: string = argv === "" ? "0xf75be6f9418710fd516fa82afb3aad07e11a0f1b" : argv;
+      const moduleId: string = argv === "" ? "0x04c5b23e82ddf058cf5e9e0ca028ff04faf17238" : argv;
```
Comment (thedarkjester) [inline sdk/examples/module/moduleExamples.ts]: consider making `0x04c5b23e82ddf058cf5e9e0ca028ff04faf17238` a constant e.g. `DEFAULT_EXAMPLE_MODULE_ID`

File: sdk/examples/portal/portalExamples.ts [hunk 2]
```diff
@@ -10,79 +10,47 @@ export default class PortalExamples {
 
   async run(argv: string, methodName: string = "", waitForConfirmation = false) {
     if (methodName.toLowerCase() == "findOneById".toLowerCase() || methodName == "") {
-      const portalId: string = argv === "" ? "0x1495341ab1019798dd08976f4a3e5ab0e095510b" : argv;
+      const portalId: string = argv === "" ? "0x24d3c0ce6d1c707294ed74309e3db9a4b95dd26a" : argv;
```
Comment (thedarkjester) [inline sdk/examples/portal/portalExamples.ts]: Same constant idea here

**Review by thedarkjester — COMMENTED** [review]
there are a few values that could be served better as constants
